# @Author: Brogan Miner <Brogan>
# @Date:   2019-03-28T12:53:16-07:00
# @Email:  brogan.miner@oregonstate.edu
# @Last modified by:   Brogan
# @Last modified time: 2019-03-28T12:56:21-07:00

language: node_js
node_js:
    - "10"

cache:
  directories:
      - node_modules

script:
- |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run build
  else
    npm run build-stage
  fi

deploy:
- provider: pages
  local-dir: dist/
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  # fqdn: map.sustainability.oregonstate.edu
- provider: s3
  access_key_id: $S3_ACCESS_ID
  secret_access_key: $S3_ACCESS_KEY
  bucket: "sustainability-map"
  skip_cleanup: true
  local_dir: dist
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master
